Fix build
Fresh builds got:
 In file included from ../src/xdp-utils.c:30:0:
 ../src/request.h:24:22: fatal error: xdp-dbus.h: No such file or directory
 compilation terminated.

Due to xdp-utils.c => request.h => xdp-dbus.h which is not yet generated
when xdp-utils.c is included from document-portal/

Just remove this as it is no longer needed.